import { catalogueSchema, type Catalogue, type Offering } from "@/domain/recommendations";

const verifiedV1 = "2026-09-17";
const verifiedV2 = "2026-09-20";

type OfferingSeed = Omit<Offering, "active" | "pricingTreatment" | "sourceLabel" | "verifiedAt" | "reviewedBy" | "reviewState" | "commercialStatus" | "prerequisites" | "caveats"> & Partial<Pick<Offering, "active" | "verifiedAt" | "reviewState" | "commercialStatus" | "prerequisites" | "caveats">>;

function offering(seed: OfferingSeed): Offering {
  const unavailable = seed.classification === "unavailable/unverified";
  return {
    active: !unavailable,
    pricingTreatment: "verify_current_quote",
    sourceLabel: "Official Exabytes source",
    verifiedAt: verifiedV2,
    reviewedBy: "MajuPilot catalogue review",
    reviewState: unavailable ? "unavailable" : "approved",
    commercialStatus: unavailable ? "unavailable" : "quote_required",
    prerequisites: [],
    caveats: ["Confirm current availability, scope, plan details, and terms with Exabytes."],
    ...seed,
  };
}

const legacyOfferings: OfferingSeed[] = [
  { id: "exb_freshsales_crm", provider: "Freshworks via Exabytes", name: "Freshsales CRM", classification: "partner/resold product", capabilityIds: ["shared_customer_operations"], approvedFactSummary: "Centralises customer information and interactions; supports sales pipelines, activities, follow-up, reports, workflows, and multi-channel engagement.", relativeCostTier: 2, sourceReferenceId: "EXB-FRESHSALES", sourceUrl: "https://www.exabytes.my/freshworks/freshsales-crm", catalogueVersion: "1.0.0" },
  { id: "exb_acronis_cyber_protect", provider: "Acronis via Exabytes", name: "Acronis Cyber Protect", classification: "partner/resold product", capabilityIds: ["protected_business_continuity"], approvedFactSummary: "Combines backup/recovery with endpoint cyber protection and centralised protection management across physical, virtual, and cloud environments.", relativeCostTier: 1, sourceReferenceId: "EXB-ACRONIS", sourceUrl: "https://www.exabytes.my/acronis/cyber-protect", catalogueVersion: "1.0.0" },
  { id: "exb_business_email", provider: "Exabytes", name: "EBiz Mail Pro Business Email", classification: "Exabytes product", capabilityIds: ["professional_team_collaboration"], approvedFactSummary: "Provides domain-based business email, web access, calendars/tasks/contacts, anti-spam, and team-sharing functions.", relativeCostTier: 1, sourceReferenceId: "EXB-EMAIL", sourceUrl: "https://www.exabytes.my/email/email-hosting", catalogueVersion: "1.0.0" },
  { id: "exb_lark", provider: "Lark via Exabytes", name: "Lark", classification: "partner/resold product", capabilityIds: ["professional_team_collaboration"], approvedFactSummary: "Exabytes offers Lark as a team collaboration and work-management option; exact inclusions depend on the current plan.", relativeCostTier: 1, sourceReferenceId: "EXB-LARK", sourceUrl: "https://www.exabytes.my/lark", catalogueVersion: "1.0.0" },
  { id: "exb_google_workspace", provider: "Google via Exabytes", name: "Google Workspace", classification: "partner/resold product", capabilityIds: ["professional_team_collaboration"], approvedFactSummary: "Provides custom business email, cloud files, real-time document collaboration, meetings, administration, and security controls.", relativeCostTier: 1, sourceReferenceId: "EXB-GWS", sourceUrl: "https://www.exabytes.my/google-workspace", catalogueVersion: "1.0.0" },
  { id: "exb_microsoft_365", provider: "Microsoft via Exabytes", name: "Microsoft 365", classification: "partner/resold product", capabilityIds: ["professional_team_collaboration"], approvedFactSummary: "Provides business email, Office tools, OneDrive storage, and collaboration tooling; exact inclusions depend on plan.", relativeCostTier: 1, sourceReferenceId: "EXB-M365", sourceUrl: "https://www.exabytes.my/microsoft-365", catalogueVersion: "1.0.0" },
  { id: "exb_ai_business_hosting", provider: "Exabytes", name: "AI-Powered Business Hosting", classification: "Exabytes product", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "Provides managed website-hosting foundations with site-building tools, SSL, and backup; exact resources and AI tools depend on plan.", relativeCostTier: 1, sourceReferenceId: "EXB-BIZHOST", sourceUrl: "https://www.exabytes.my/web-hosting/business-web-hosting", catalogueVersion: "1.0.0" },
  { id: "exb_cloudflare_managed", provider: "Cloudflare via Exabytes", name: "Cloudflare Managed Services", classification: "partner/resold product", capabilityIds: ["protected_web_presence"], approvedFactSummary: "Provides website performance and protection capabilities including CDN, DDoS mitigation, SSL compatibility, and WAF features depending on plan.", relativeCostTier: 2, sourceReferenceId: "EXB-CLOUDFLARE", sourceUrl: "https://www.exabytes.my/web-security/cloudflare-web-performance-booster", catalogueVersion: "1.0.0" },
  { id: "exb_vision_cloud", provider: "Exabytes", name: "Exabytes Vision Cloud", classification: "Exabytes product", capabilityIds: ["scalable_cloud_operations"], approvedFactSummary: "A managed, Malaysia-hosted virtual infrastructure option for production workloads, dedicated virtual resources, networking, monitoring, and optional backup/disaster recovery.", relativeCostTier: 4, sourceReferenceId: "EXB-EVC", sourceUrl: "https://www.exabytes.my/enterprise/evc", catalogueVersion: "1.0.0", commercialStatus: "consultation_only" },
  { id: "exb_ai_cloud", provider: "Exabytes", name: "Exabytes AI Cloud", classification: "Exabytes product", capabilityIds: ["governed_ai_automation"], approvedFactSummary: "Combines cloud infrastructure with workflow automation and AI tooling in a Malaysia-hosted platform.", relativeCostTier: 3, sourceReferenceId: "EXB-AICLOUD", sourceUrl: "https://www.exabytes.ai/ai-cloud", catalogueVersion: "1.0.0", commercialStatus: "register_interest" },
  { id: "exb_eva", provider: "Exabytes", name: "Exabytes Vision AI (EVA)", classification: "Exabytes product", capabilityIds: ["governed_ai_automation"], approvedFactSummary: "A no-code agentic AI platform for visually building agents grounded in business knowledge and connected to apps/data.", relativeCostTier: 3, sourceReferenceId: "EXB-EVA", sourceUrl: "https://www.exabytes.ai/eva", catalogueVersion: "1.0.0", commercialStatus: "register_interest" },
];

const legacyMappings = [
  ["shared_customer_operations", "exb_freshsales_crm", "catalogue_rule_1", "Freshsales CRM is the active catalogue mapping for shared customer operations."],
  ["protected_business_continuity", "exb_acronis_cyber_protect", "catalogue_rule_2", "Acronis Cyber Protect combines the backup/recovery and protection capabilities this capability requires."],
  ["professional_team_collaboration", "exb_business_email", "catalogue_rule_3_email", "EBiz Mail Pro fits an absent professional-email foundation when cost is the highest concern."],
  ["professional_team_collaboration", "exb_lark", "catalogue_rule_3_lark", "Lark is an allowed collaboration option when coordination and workflow are the dominant evidenced gap."],
  ["professional_team_collaboration", "exb_google_workspace", "catalogue_rule_3_google", "Google Workspace requires an explicit browser-first shared-files preference."],
  ["professional_team_collaboration", "exb_microsoft_365", "catalogue_rule_3_microsoft", "Microsoft 365 requires an explicit Office or Outlook compatibility need."],
  ["measurable_digital_growth", "exb_ai_business_hosting", "catalogue_rule_4", "AI-Powered Business Hosting is eligible only when an owned website/store foundation is missing or informal."],
  ["protected_web_presence", "exb_cloudflare_managed", "catalogue_rule_5", "Cloudflare Managed Services is eligible only for an active website with an evidenced protection gap."],
  ["scalable_cloud_operations", "exb_vision_cloud", "catalogue_rule_6", "Exabytes Vision Cloud is eligible only for an evidenced production infrastructure or scaling need."],
  ["governed_ai_automation", "exb_ai_cloud", "catalogue_rule_7", "Exabytes AI Cloud is the default future-fit offering for governed AI automation."],
] as const;

export const EXABYTES_CATALOGUE_1_0_0: Catalogue = catalogueSchema.parse({
  version: "1.0.0",
  reviewState: "retired",
  verifiedAt: verifiedV1,
  offerings: legacyOfferings.map((entry) => offering({ ...entry, verifiedAt: verifiedV1 })),
  mappings: legacyMappings.map(([capabilityId, offeringId, selectionRuleId, mappingReason]) => ({ capabilityId, offeringId, selectionRuleId, mappingReason })),
});

const carriedForward = legacyOfferings.map((entry) => offering({ ...entry, catalogueVersion: "2.0.0", verifiedAt: verifiedV2 }));
const additions: Offering[] = [
  offering({ id: "exb_ai_wp_hosting", provider: "Exabytes", name: "AI-Powered WP Hosting", classification: "Exabytes product", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "WordPress-oriented hosting with WordPress setup and management tools, AI-assisted site/content tools, SSL, and backup features that vary by plan.", relativeCostTier: 1, sourceReferenceId: "EXB-WP", sourceUrl: "https://www.exabytes.my/web-hosting/wp-hosting", catalogueVersion: "2.0.0", prerequisites: ["A missing or informal owned website foundation", "A confirmed WordPress preference or compatibility need"] }),
  offering({ id: "exb_managed_ecommerce", provider: "Exabytes", name: "Managed eCommerce Solution", classification: "Exabytes product", capabilityIds: ["measurable_digital_growth", "shared_customer_operations"], approvedFactSummary: "A managed commerce path covering website, marketplace integration, store operations, customer care, marketing, reporting, and consultation; exact scope requires confirmation.", relativeCostTier: 4, sourceReferenceId: "EXB-ECOM", sourceUrl: "https://www.exabytes.my/managed-ecommerce-solution", catalogueVersion: "2.0.0", commercialStatus: "consultation_only", prerequisites: ["A confirmed commerce operating need", "Consultant validation of channels, catalogue size, fulfilment, and ownership"] }),
  offering({ id: "exb_shopify_partner_path", provider: "Exabytes partner directory", name: "Shopify Partner implementation path", classification: "supported path", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "An official Exabytes partner-directory listing identifies a Shopify Partner; this supports only a consultant-validated implementation path, not an Exabytes Shopify SKU.", relativeCostTier: 3, sourceReferenceId: "EXB-SHOPIFY", sourceUrl: "https://www.exabytes.my/partners/home/listing/mices-technology-sdn-bhd/", catalogueVersion: "2.0.0", commercialStatus: "consultation_only", prerequisites: ["An explicit Shopify requirement", "Consultant validation of the current partner relationship and scope"] }),
  offering({ id: "unavailable_magento_path", provider: "Unverified", name: "Magento-specific implementation", classification: "unavailable/unverified", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "No current official Exabytes product or supported-path page was verified for a Magento-specific implementation.", relativeCostTier: 4, sourceReferenceId: "EXB-MAGENTO-UNVERIFIED", sourceUrl: null, catalogueVersion: "2.0.0", caveats: ["Do not map or recommend until a current official Exabytes source is reviewed."] }),
  offering({ id: "third_party_ecommerce_saas", provider: "Third party", name: "Generic third-party eCommerce SaaS", classification: "third-party alternative", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "A category-only non-Exabytes alternative. No provider, endorsement, features, integration, or commercial terms are asserted.", relativeCostTier: 2, sourceReferenceId: "CATEGORY-THIRD-PARTY-ECOMMERCE", sourceUrl: null, catalogueVersion: "2.0.0", active: false, reviewState: "disabled", commercialStatus: "consultation_only", caveats: ["Do not imply Exabytes sale, support, endorsement, or integration."] }),
  offering({ id: "exb_meeting_ai", provider: "Exabytes", name: "Meeting AI", classification: "Exabytes product", capabilityIds: ["governed_ai_automation", "professional_team_collaboration"], approvedFactSummary: "A register-interest AI meeting assistant that joins calls and produces shareable summaries, action items, and next steps.", relativeCostTier: 2, sourceReferenceId: "EXB-GROWAI", sourceUrl: "https://www.exabytes.ai/", catalogueVersion: "2.0.0", commercialStatus: "register_interest", prerequisites: ["Governed AI prerequisites are met", "Meeting recording, consent, retention, and human-review controls are confirmed"] }),
  offering({ id: "exb_ai_sales_team", provider: "Exabytes", name: "AI Sales Team", classification: "Exabytes product", capabilityIds: ["governed_ai_automation", "shared_customer_operations"], approvedFactSummary: "A consultation-led AI-agent team for sales research, outreach, qualification, follow-up, enablement, CRM data, and reporting, with people retaining relationship and closing work.", relativeCostTier: 3, sourceReferenceId: "EXB-SALES", sourceUrl: "https://www.exabytes.ai/ai-sales-team", catalogueVersion: "2.0.0", commercialStatus: "register_interest", prerequisites: ["Governed AI prerequisites are met", "A defined sales process, usable customer data, human oversight, and approved outreach controls"] }),
  offering({ id: "exb_ai_marketing_team", provider: "Exabytes", name: "AI Digital Marketing Team Agent", classification: "Exabytes product", capabilityIds: ["governed_ai_automation", "measurable_digital_growth"], approvedFactSummary: "A register-interest AI marketing-agent team positioned for coordinated brand, traffic, content, campaign, and lead-conversion work.", relativeCostTier: 3, sourceReferenceId: "EXB-MARKETING", sourceUrl: "https://www.exabytes.ai/ai-marketing-team", catalogueVersion: "2.0.0", commercialStatus: "register_interest", prerequisites: ["Governed AI prerequisites are met", "Brand, approval, measurement, and human-review workflows are defined"] }),
  offering({ id: "exb_freshmarketer", provider: "Freshworks via Exabytes", name: "Freshmarketer", classification: "partner/resold product", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "An Exabytes-offered Freshworks campaign path with email and multichannel marketing, journey, tracking, segmentation, reporting, and plan-dependent AI features.", relativeCostTier: 2, sourceReferenceId: "EXB-FRESHSALES", sourceUrl: "https://www.exabytes.my/freshworks/freshsales-crm", catalogueVersion: "2.0.0", prerequisites: ["A confirmed campaign automation and measurement gap", "Current plan capabilities are reviewed"] }),
  offering({ id: "exb_freshdesk", provider: "Freshworks via Exabytes", name: "Freshdesk", classification: "partner/resold product", capabilityIds: ["shared_customer_operations"], approvedFactSummary: "An Exabytes-offered helpdesk path for ticketing, shared inboxes, knowledge base, customer portals, reporting, automation, and plan-dependent Freddy AI capabilities.", relativeCostTier: 2, sourceReferenceId: "EXB-FRESHDESK", sourceUrl: "https://www.exabytes.my/freshworks/helpdesk", catalogueVersion: "2.0.0", prerequisites: ["A confirmed customer-support volume or channel-management need", "Current plan and AI inclusions are reviewed"] }),
  offering({ id: "exb_freshchat", provider: "Freshworks via Exabytes", name: "Freshchat", classification: "partner/resold product", capabilityIds: ["shared_customer_operations"], approvedFactSummary: "A conversational support and live-chat path within the Freshworks portfolio offered by Exabytes; exact current plan capabilities require review.", relativeCostTier: 2, sourceReferenceId: "EXB-FRESHWORKS", sourceUrl: "https://www.exabytes.my/freshworks", catalogueVersion: "2.0.0", prerequisites: ["A confirmed real-time customer messaging need", "Current plan and channel support are reviewed"] }),
  offering({ id: "exb_ai_website_builder_path", provider: "Exabytes", name: "AI Website Builder path", classification: "supported path", capabilityIds: ["measurable_digital_growth"], approvedFactSummary: "AI-assisted website and content creation is a reviewed capability within Exabytes Business Hosting; it is modelled as a supported path, not a separate SKU.", relativeCostTier: 1, sourceReferenceId: "EXB-BIZHOST", sourceUrl: "https://www.exabytes.my/web-hosting/business-web-hosting", catalogueVersion: "2.0.0", prerequisites: ["A missing or informal owned website foundation", "The hosting plan's current builder inclusions are confirmed"] }),
  offering({ id: "exb_bespoke_ai_consultation", provider: "Exabytes", name: "Bespoke AI and integration consultation", classification: "consultation-only", capabilityIds: ["governed_ai_automation", "shared_customer_operations", "measurable_digital_growth"], approvedFactSummary: "A consultation-only route for needs that do not fit a verified product mapping; no SKU, features, price, or delivery outcome is implied.", relativeCostTier: 4, sourceReferenceId: "EXB-GROWAI", sourceUrl: "https://www.exabytes.ai/", catalogueVersion: "2.0.0", commercialStatus: "consultation_only", prerequisites: ["No verified product mapping adequately fits", "A consultant validates scope, data, security, ownership, and delivery assumptions"] }),
];

const addedMappings = [
  ["measurable_digital_growth", "exb_ai_wp_hosting", "catalogue_rule_8_wp", "Managed WordPress is eligible only for a missing or informal website foundation and a confirmed WordPress path."],
  ["measurable_digital_growth", "exb_managed_ecommerce", "catalogue_rule_9_ecommerce", "Managed eCommerce is a consultation-led path for an evidenced commerce operating need."],
  ["measurable_digital_growth", "exb_shopify_partner_path", "catalogue_rule_10_shopify", "The Shopify path is consultant-validated and is not represented as an Exabytes SKU."],
  ["governed_ai_automation", "exb_meeting_ai", "catalogue_rule_11_meeting_ai", "Meeting AI is eligible only after governed-AI prerequisites and meeting-data controls pass."],
  ["governed_ai_automation", "exb_ai_sales_team", "catalogue_rule_12_ai_sales", "AI Sales Team is eligible only for an evidenced sales need after governed-AI prerequisites pass."],
  ["governed_ai_automation", "exb_ai_marketing_team", "catalogue_rule_13_ai_marketing", "AI Digital Marketing Team is eligible only for an evidenced growth need after governed-AI prerequisites pass."],
  ["measurable_digital_growth", "exb_freshmarketer", "catalogue_rule_14_freshmarketer", "Freshmarketer is an alternative for an evidenced campaign automation and measurement gap."],
  ["shared_customer_operations", "exb_freshdesk", "catalogue_rule_15_freshdesk", "Freshdesk is an alternative for evidenced multi-channel support operations."],
  ["shared_customer_operations", "exb_freshchat", "catalogue_rule_16_freshchat", "Freshchat is an alternative for evidenced conversational support."],
  ["measurable_digital_growth", "exb_ai_website_builder_path", "catalogue_rule_17_builder", "The AI Website Builder path is a hosting capability, not a standalone SKU."],
  ["governed_ai_automation", "exb_bespoke_ai_consultation", "catalogue_rule_18_bespoke", "Use a consultation-only route when no verified product mapping adequately fits."],
] as const;

export const EXABYTES_CATALOGUE_2_0_0: Catalogue = catalogueSchema.parse({
  version: "2.0.0",
  reviewState: "active",
  verifiedAt: verifiedV2,
  offerings: [...carriedForward, ...additions],
  mappings: [...legacyMappings, ...addedMappings].map(([capabilityId, offeringId, selectionRuleId, mappingReason]) => ({ capabilityId, offeringId, selectionRuleId, mappingReason })),
});

export const EXABYTES_CATALOGUE_CURRENT = EXABYTES_CATALOGUE_2_0_0;
