import { PersistenceError, type ArtifactWrite, type AssessmentAnswerRecord, type ConsentAppend, type DataRequest, type GuestSessionReceipt, type OwnershipContext } from "@/domain/persistence";
import type { PersistenceRepository } from "./repository";

type Guest = { id:string; digest:string; assessmentSessionId:string; expiresAt:string; revoked:boolean; claimed?:{userId:string;organizationId:string} };
export class LocalFixturePersistenceRepository implements PersistenceRepository {
  readonly transaction="local-fixture" as const; private guests=new Map<string,Guest>(); private memberships=new Map<string,OwnershipContext>();
  readonly answers=new Map<string,AssessmentAnswerRecord>(); readonly artifacts=new Map<string,ArtifactWrite>(); readonly consents=new Map<string,ConsentAppend>(); readonly requests=new Map<string,Record<string,unknown>>();
  addMembership(owner:Extract<OwnershipContext,{kind:"organization"}>){this.memberships.set(`${owner.userId}:${owner.organizationId}`,owner);}
  async issueGuest(tokenDigest:string){const guestSessionId=crypto.randomUUID(),assessmentSessionId=crypto.randomUUID(),expiresAt=new Date(Date.now()+86400000).toISOString(),absoluteExpiresAt=new Date(Date.now()+2592000000).toISOString();this.guests.set(tokenDigest,{id:guestSessionId,digest:tokenDigest,assessmentSessionId,expiresAt,revoked:false});return{guestSessionId,assessmentSessionId,expiresAt,absoluteExpiresAt};}
  async resumeGuest(tokenDigest:string,newDigest:string){const g=this.guests.get(tokenDigest);if(!g||g.revoked)throw new PersistenceError("UNAUTHENTICATED",401);if(Date.parse(g.expiresAt)<=Date.now())throw new PersistenceError("SESSION_EXPIRED",401);this.guests.delete(tokenDigest);g.digest=newDigest;g.expiresAt=new Date(Date.now()+86400000).toISOString();this.guests.set(newDigest,g);return{guestSessionId:g.id,assessmentSessionId:g.assessmentSessionId,expiresAt:g.expiresAt};}
  async revokeGuest(tokenDigest:string){const g=this.guests.get(tokenDigest);if(!g)throw new PersistenceError("UNAUTHENTICATED",401);g.revoked=true;}
  async resolveGuest(tokenDigest:string){const g=this.guests.get(tokenDigest);if(!g||g.revoked||g.claimed)throw new PersistenceError("UNAUTHENTICATED",401);if(Date.parse(g.expiresAt)<=Date.now())throw new PersistenceError("SESSION_EXPIRED",401);return{kind:"guest" as const,guestSessionId:g.id,assessmentSessionId:g.assessmentSessionId};}
  async claimGuest(tokenDigest:string,userId:string,organizationId:string):Promise<GuestSessionReceipt>{const member=this.memberships.get(`${userId}:${organizationId}`);if(!member)throw new PersistenceError("FORBIDDEN",403);const g=this.guests.get(tokenDigest);if(!g)throw new PersistenceError("UNAUTHENTICATED",401);if(g.claimed){if(g.claimed.userId===userId&&g.claimed.organizationId===organizationId)return{guestSessionId:g.id,assessmentSessionId:g.assessmentSessionId,expiresAt:new Date().toISOString(),replayed:true};throw new PersistenceError("CLAIM_CONFLICT",409);}g.claimed={userId,organizationId};g.revoked=true;return{guestSessionId:g.id,assessmentSessionId:g.assessmentSessionId,expiresAt:new Date().toISOString(),replayed:false};}
  async resolveMembership(userId:string,organizationId:string){const owner=this.memberships.get(`${userId}:${organizationId}`);if(!owner)throw new PersistenceError("FORBIDDEN",403);return owner;}
  async saveAnswer(_owner:OwnershipContext,r:AssessmentAnswerRecord){this.answers.set(r.id,r);} async saveArtifact(_owner:OwnershipContext,r:ArtifactWrite){this.artifacts.set(r.id,r);} async appendConsent(_owner:OwnershipContext,r:ConsentAppend){this.consents.set(r.id,r);}
  async createExport(_owner:OwnershipContext,r:DataRequest){this.requests.set(r.id,{id:r.id,status:"pending",created_at:new Date().toISOString(),updated_at:new Date().toISOString()});return r.id;}
  async createDeletion(_owner:OwnershipContext,r:DataRequest){const receipt=crypto.randomUUID();this.requests.set(r.id,{id:r.id,status:"pending",safe_receipt:receipt,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});return receipt;}
  async getDataRequest(_owner:OwnershipContext,_kind:"export"|"deletion",id:string){const value=this.requests.get(id);if(!value)throw new PersistenceError("NOT_FOUND",404);return value;}
}
