import "server-only";
import { PersistenceError, type ArtifactWrite, type AssessmentAnswerRecord, type ConsentAppend, type DataRequest, type GuestSessionReceipt, type OrganizationRole, type OwnershipContext } from "@/domain/persistence";
import { createAdminSupabaseClient } from "@/infrastructure/supabase/admin";
import type { PersistenceRepository } from "./repository";
import type { ModelCallTelemetry } from "@/domain/ai-execution";
import type { RecommendationExplanationContext } from "@/domain/recommendation-explanations";
import { recommendationResultSchema, type CapabilityId } from "@/domain/recommendations";

type RpcRow = Record<string, unknown>;
const first = (data: unknown): RpcRow => Array.isArray(data) ? (data[0] as RpcRow) : (data as RpcRow);
function dbError(error: { message: string; code?: string } | null): never {
  const message = error?.message ?? "";
  if (message.includes("SESSION_EXPIRED")) throw new PersistenceError("SESSION_EXPIRED",401,{cause:error});
  if (message.includes("SESSION_REVOKED") || message.includes("SESSION_NOT_FOUND")) throw new PersistenceError("UNAUTHENTICATED",401,{cause:error});
  if (message.includes("CLAIM_CONFLICT")) throw new PersistenceError("CLAIM_CONFLICT",409,{cause:error});
  if (message.includes("FORBIDDEN") || error?.code === "42501") throw new PersistenceError("FORBIDDEN",403,{cause:error});
  throw new PersistenceError("INTERNAL_RETRYABLE",503,{cause:error});
}
const iso = (v: unknown) => String(v);

export class SupabasePersistenceRepository implements PersistenceRepository {
  private readonly db = createAdminSupabaseClient();
  async issueGuest(tokenDigest: string): Promise<GuestSessionReceipt> {
    const { data,error }=await this.db.rpc("issue_guest_session",{p_token_digest:tokenDigest,p_schema_version:"1.0.0"}); if(error) dbError(error); const r=first(data);
    return {guestSessionId:String(r.guest_session_id),assessmentSessionId:String(r.assessment_session_id),expiresAt:iso(r.expires_at),absoluteExpiresAt:iso(r.absolute_expires_at)};
  }
  async resumeGuest(tokenDigest:string,newDigest:string):Promise<GuestSessionReceipt>{const{data,error}=await this.db.rpc("resume_rotate_guest_session",{p_token_digest:tokenDigest,p_new_token_digest:newDigest});if(error)dbError(error);const r=first(data);return{guestSessionId:String(r.guest_session_id),assessmentSessionId:String(r.assessment_session_id),expiresAt:iso(r.expires_at)};}
  async revokeGuest(tokenDigest:string){const{error}=await this.db.rpc("revoke_guest_session",{p_token_digest:tokenDigest});if(error)dbError(error);}
  async resolveGuest(tokenDigest:string){const{data,error}=await this.db.from("guest_sessions").select("id,expires_at,absolute_expires_at,revoked_at,claimed_at").eq("token_digest",tokenDigest).maybeSingle();if(error)dbError(error);if(!data)throw new PersistenceError("UNAUTHENTICATED",401);const now=Date.now();if(data.revoked_at||data.claimed_at)throw new PersistenceError("UNAUTHENTICATED",401);if(Date.parse(data.expires_at)<=now||Date.parse(data.absolute_expires_at)<=now)throw new PersistenceError("SESSION_EXPIRED",401);const a=await this.db.from("assessment_sessions").select("id").eq("guest_session_id",data.id).maybeSingle();if(a.error)dbError(a.error);if(!a.data)throw new PersistenceError("NOT_FOUND",404);return{kind:"guest" as const,guestSessionId:data.id,assessmentSessionId:a.data.id};}
  async claimGuest(tokenDigest:string,userId:string,organizationId:string){const{data,error}=await this.db.rpc("claim_guest_session",{p_token_digest:tokenDigest,p_user_id:userId,p_organization_id:organizationId});if(error)dbError(error);const r=first(data);return{guestSessionId:String(r.guest_session_id),assessmentSessionId:String(r.assessment_session_id),expiresAt:iso(r.claimed_at),replayed:Boolean(r.replayed)};}
  async resolveMembership(userId:string,organizationId:string):Promise<OwnershipContext>{const{data,error}=await this.db.from("organization_members").select("role,status").eq("user_id",userId).eq("organization_id",organizationId).maybeSingle();if(error)dbError(error);if(!data||data.status!=="active")throw new PersistenceError("FORBIDDEN",403);return{kind:"organization",userId,organizationId,role:data.role as OrganizationRole};}
  async assertAssessmentAccess(owner:OwnershipContext,id:string){let q=this.db.from("assessment_sessions").select("id").eq("id",id);q=owner.kind==="guest"?q.eq("guest_session_id",owner.guestSessionId):q.eq("organization_id",owner.organizationId);const{data,error}=await q.maybeSingle();if(error)dbError(error);if(!data)throw new PersistenceError("NOT_FOUND",404);}
  async assertEvidenceReferences(owner:OwnershipContext,assessmentSessionId:string,evidenceRefs:string[]){await this.assertAssessmentAccess(owner,assessmentSessionId);const unique=[...new Set(evidenceRefs)];if(!unique.length)return;const{data,error}=await this.db.from("evidence_items").select("id").eq("assessment_session_id",assessmentSessionId).in("id",unique);if(error)dbError(error);if(!data||new Set(data.map((row)=>row.id)).size!==unique.length)throw new PersistenceError("NOT_FOUND",404);}
  async countDeliveredFollowUps(owner:OwnershipContext,assessmentSessionId:string){await this.assertAssessmentAccess(owner,assessmentSessionId);let q=this.db.from("model_calls").select("id",{count:"exact",head:true}).eq("assessment_session_id",assessmentSessionId).eq("operation","assessment_follow_up").in("outcome",["success","deterministic_fallback","ai_disabled"]);if(owner.kind==="organization")q=q.eq("organization_id",owner.organizationId);const{count,error}=await q;if(error)dbError(error);return count??0;}
  async loadRecommendationForExplanation(owner:OwnershipContext,assessmentSessionId:string,recommendationRunId:string,capabilityId:CapabilityId,evidenceRefs:string[]):Promise<Omit<RecommendationExplanationContext,"catalogueSources">>{await this.assertEvidenceReferences(owner,assessmentSessionId,evidenceRefs);const{data,error}=await this.db.from("recommendation_runs").select("id,payload").eq("id",recommendationRunId).eq("assessment_session_id",assessmentSessionId).maybeSingle();if(error)dbError(error);if(!data)throw new PersistenceError("NOT_FOUND",404);const result=recommendationResultSchema.safeParse(data.payload);if(!result.success)throw new PersistenceError("NOT_FOUND",404);const recommendation=result.data.recommendations.find((item)=>item.capabilityId===capabilityId);if(!recommendation)throw new PersistenceError("NOT_FOUND",404);const{data:evidenceRows,error:evidenceError}=await this.db.from("evidence_items").select("id,source_ref,payload").eq("assessment_session_id",assessmentSessionId).in("id",evidenceRefs);if(evidenceError)dbError(evidenceError);const evidence=(evidenceRows??[]).map((row)=>{const payload=row.payload&&typeof row.payload==="object"?row.payload as Record<string,unknown>:{};return{id:row.id,sourceRef:String(row.source_ref),normalizedValue:payload.normalizedValue??payload.value??"Recorded evidence"};});return{recommendationId:recommendationRunId,recommendation,evidence};}
  async saveAnswer(owner:OwnershipContext,record:AssessmentAnswerRecord){await this.assertAssessmentAccess(owner,record.assessmentSessionId);const{error}=await this.db.from("assessment_answers").insert({id:record.id,assessment_session_id:record.assessmentSessionId,answer_key:record.answerKey,revision:record.revision,value:record.value,evidence_state:record.evidenceState,supersedes_id:record.supersedesId??null,schema_version:record.schemaVersion,created_by:owner.kind==="organization"?owner.userId:null});if(error)dbError(error);}
  async saveArtifact(owner:OwnershipContext,r:ArtifactWrite){await this.assertAssessmentAccess(owner,r.assessmentSessionId);const common={id:r.id,assessment_session_id:r.assessmentSessionId,schema_version:r.schemaVersion};let row:Record<string,unknown>={...common};switch(r.kind){case"business_twins":row={...common,revision:r.revision,payload:r.payload,source_artifact_ids:r.sourceArtifactIds,rule_pack_version:r.rulePackVersion,created_by:owner.kind==="organization"?owner.userId:null};break;case"evidence_items":row={...common,revision:r.revision,source_kind:r.payload.sourceKind,source_ref:r.payload.sourceRef,payload:r.payload,status:"active",business_twin_id:r.links.businessTwinId??null};break;case"diagnostic_runs":row={...common,business_twin_id:r.links.businessTwinId,payload:r.payload,rule_pack_version:r.rulePackVersion,source_artifact_ids:r.sourceArtifactIds};break;case"recommendation_runs":row={...common,diagnostic_run_id:r.links.diagnosticRunId,business_twin_id:r.links.businessTwinId,catalogue_version_id:r.links.catalogueVersionId??null,payload:r.payload,rule_pack_version:r.rulePackVersion,source_artifact_ids:r.sourceArtifactIds};break;case"scenario_comparisons":row={...common,recommendation_run_id:r.links.recommendationRunId,business_twin_id:r.links.businessTwinId,rule_pack_version:r.rulePackVersion};break;case"scenario_revisions":delete row.assessment_session_id;row={id:r.id,scenario_comparison_id:r.links.scenarioComparisonId,revision:r.revision,assumptions:r.payload.assumptions,results:r.payload.results,source_artifact_ids:r.sourceArtifactIds,schema_version:r.schemaVersion,created_by:owner.kind==="organization"?owner.userId:null};break;case"blueprints":row={...common,revision:r.revision,business_twin_id:r.links.businessTwinId,diagnostic_run_id:r.links.diagnosticRunId,recommendation_run_id:r.links.recommendationRunId,scenario_revision_id:r.links.scenarioRevisionId,catalogue_version_id:r.links.catalogueVersionId??null,payload:r.payload,rule_pack_version:r.rulePackVersion,source_artifact_ids:r.sourceArtifactIds,provenance_hash:r.payload.provenanceHash,created_by:owner.kind==="organization"?owner.userId:null};break;}const{error}=await this.db.from(r.kind).insert(row);if(error)dbError(error);}
  async appendConsent(owner:OwnershipContext,r:ConsentAppend){await this.assertAssessmentAccess(owner,r.assessmentSessionId);const{error}=await this.db.from("consent_records").insert({id:r.id,assessment_session_id:r.assessmentSessionId,organization_id:owner.kind==="organization"?owner.organizationId:null,subject_kind:owner.kind==="guest"?"guest_session":"user",subject_id:owner.kind==="guest"?owner.guestSessionId:owner.userId,purpose:r.purpose,action:r.action,consent_version:r.consentVersion,policy_version:r.policyVersion,text_hash:r.textHash,locale:r.locale,presentation_surface:r.presentationSurface,parent_consent_id:r.parentConsentId??null,request_id:r.requestId,channel:r.channel});if(error)dbError(error);}
  async createExport(owner:OwnershipContext,r:DataRequest){const{error}=await this.db.from("export_requests").insert({id:r.id,organization_id:owner.kind==="organization"?owner.organizationId:null,requested_by:owner.kind==="organization"?owner.userId:null,assessment_session_id:r.assessmentSessionId??null,retention_policy_version:r.retentionPolicyVersion,request_id:crypto.randomUUID()});if(error)dbError(error);return r.id;}
  async createDeletion(owner:OwnershipContext,r:DataRequest){const hold=await this.db.from("retention_holds").select("id").is("released_at",null).or(`organization_id.eq.${r.organizationId??"00000000-0000-0000-0000-000000000000"},assessment_session_id.eq.${r.assessmentSessionId??"00000000-0000-0000-0000-000000000000"}`).limit(1);if(hold.error)dbError(hold.error);if(hold.data.length)throw new PersistenceError("RETENTION_HOLD",409);const receipt=crypto.randomUUID();const{error}=await this.db.from("deletion_requests").insert({id:r.id,organization_id:owner.kind==="organization"?owner.organizationId:null,requested_by:owner.kind==="organization"?owner.userId:null,assessment_session_id:r.assessmentSessionId??null,retention_policy_version:r.retentionPolicyVersion,safe_receipt:receipt});if(error)dbError(error);return receipt;}
  async getDataRequest(owner:OwnershipContext,kind:"export"|"deletion",id:string){const table=kind==="export"?"export_requests":"deletion_requests";let q=this.db.from(table).select("id,status,created_at,updated_at,expires_at,downloaded_at,blocked_reason").eq("id",id);q=owner.kind==="organization"?q.eq("organization_id",owner.organizationId):q.eq("assessment_session_id",(await this.resolveGuestById(owner.guestSessionId)));const{data,error}=await q.maybeSingle();if(error)dbError(error);if(!data)throw new PersistenceError("NOT_FOUND",404);return data;}
  async appendModelCall(owner:OwnershipContext,r:ModelCallTelemetry){await this.assertAssessmentAccess(owner,r.assessmentSessionId);const{error}=await this.db.from("model_calls").insert({id:r.id,assessment_session_id:r.assessmentSessionId,organization_id:owner.kind==="organization"?owner.organizationId:null,operation:r.operation,provider:r.provider,model:r.model,schema_version:r.schemaVersion,prompt_version:r.promptVersion,started_at:r.startedAt,completed_at:r.completedAt,latency_ms:r.latencyMs,input_tokens:r.inputTokens,output_tokens:r.outputTokens,estimated_cost:r.estimatedCost,retry_count:r.retryCount,outcome:r.outcome,safe_error_code:r.fallbackReason,evidence_ids:r.evidenceRefs});if(error)dbError(error);}
  async getDailyModelSpend(owner:OwnershipContext){const since=new Date(Date.now()-86_400_000).toISOString();let q=this.db.from("model_calls").select("estimated_cost").gte("created_at",since);if(owner.kind==="organization")q=q.eq("organization_id",owner.organizationId);else q=q.eq("assessment_session_id",await this.resolveGuestById(owner.guestSessionId));const{data,error}=await q;if(error)dbError(error);return(data??[]).reduce((total,row)=>total+Number(row.estimated_cost??0),0);}
  private async resolveGuestById(guestSessionId:string){const{data,error}=await this.db.from("assessment_sessions").select("id").eq("guest_session_id",guestSessionId).single();if(error)dbError(error);return data.id;}
}
